name: multimodal
dependencies:
  - python==3.7.4
  - tensorflow-gpu==1.14.0
  - pandas==0.25.1
  - matplotlib==3.1.1
  - scikit-learn==0.21.3
  - keras==2.2.4
  - h5py==2.9.0
  - xlrd==1.2.0
  - jupyterlab
  - pip
  